Fix financials formatting
ranaroussi/yfinance pull request #1193
Opened 2022-11-22 22:22 UTC by ValueRaider

Add whitespace to financials tables keys, e.g. "FreeCashFlow" -> "Free Cash Flow"

Also restored @git-shogg code for creating nested index but disabled, eventually will be good to complete.

2022-11-22 22:26 UTC, git-shogg commented
@ValueRaider great job! I have another idea on how we might include the parent->child index. Will look to raise a PR at a later date.

2022-11-23 00:06 UTC, fredrik-corneliusson commented
I do not favor space separation for columns and or row names. 
The reason is as it makes working with yfinance in an interactive environment  (jupyter, ipython etc.) inconvenient as breaks double click to select column names for example.

2022-11-23 00:37 UTC, ValueRaider commented
This just restores original yfinance behaviour. I think some spacing is necessary for readability, but can switch to '_'.

2022-11-23 11:38 UTC, fredrik-corneliusson commented
Sounds like solution. 
If that is done would it be better do do the "presentation" formatting higher up in the call chain (the get_* methods in Ticker and base)? 
https://github.com/ranaroussi/yfinance/blob/ab1476c0d17d6cbc5c773541436f86b8fa917a35/yfinance/base.py#L760
That way the code internally does not need to deal with prettified indexes and column values, reducing code complexity and risks for bugs.
As a added bonus users of the API could then decide what format they want by adding a optional "raw" keyword argument or something to the API function.

2022-11-23 17:48 UTC, ValueRaider commented
Done.

Question - should the Ticker properties (e.g. `Ticker.income_stmt`) default to use this formatting? README list these as way to access financials rather than `get_*()`, but user can't pass arguments through property.

2022-11-23 23:01 UTC, fredrik-corneliusson requested changes
Nice with tests 👍 
Just some code cleanups and escaping of variables used in dynamically created regexps needed.

2022-11-24 17:08 UTC, ValueRaider commented on yfinance/utils.py
> +    rep = r"\g<1>{}\g<2>".format(sep)
I'll resolve by not allowing special characters.

2022-11-24 17:23 UTC, ValueRaider commented on yfinance/utils.py
> +        o = [_re.sub(pat, rep, i) for i in o]
What practical difference does this make?

2022-11-24 20:11 UTC, fredrik-corneliusson commented on yfinance/utils.py
> +        o = [_re.sub(pat, rep, i) for i in o]
Mainly it is the "o" name that makes the code hard to understand. it should be renamed first. It is for readability and maintainability. Also if input variable is mutable also O and 0 looks similar and is especially bad as a variabel name.
https://dev.to/alexomeyer/10-must-know-patterns-for-writing-clean-code-with-python-56bf

2022-11-24 20:37 UTC, ValueRaider commented on yfinance/utils.py
> +        o = [_re.sub(pat, rep, i) for i in o]
I agree with descriptive names, just didn't understand why it has to differ from input when it isn't mutated.

2022-11-24 22:24 UTC, fredrik-corneliusson commented on yfinance/utils.py
> +        o = [_re.sub(pat, rep, i) for i in o]
It's really not that important, it all depends on the descriptive name the variable will get, I figure.

2022-11-26 21:40 UTC, merged