Serve old financials when new financials are missing
ranaroussi/yfinance pull request #1194
Opened 2022-11-22 22:27 UTC by ValueRaider

For some tickers Yahoo does not display quarterly financials. I notice most with Australian tickers e.g. BSE.AX . https://finance.yahoo.com/quote/BSE.AX/cash-flow?p=BSE.AX

This means `yfinance` using the TimeSeries API also returns an empty table. But the old-style table is still present in QuoteTimeSeriesStore, so I propose returning this. Question - should user be alerted to switch? How?

2022-11-22 22:32 UTC, git-shogg commented
@ValueRaider good point. I am fine either way the main thing to note here is that TTM (Trailing Twelve Months) is not a quarterly type metric at all.

2022-11-23 00:21 UTC, fredrik-corneliusson commented
Do you have an example of how to test this?
I tried to test this by adding one to TestTickerMiscFinancials but it fails with exception.
```
    def test_quarterly_income_statement_old_fallback(self):
        expected_row = "TotalRevenue"
        ticker = yf.Ticker("BSE.AX")
        data = ticker.quarterly_income_stmt
        self.assertIsInstance(data, pd.DataFrame, "data has wrong type")
        self.assertFalse(data.empty, "data is empty")
        self.assertIn(expected_row, data.index, "Did not find expected row in index")

        data_cached = self.ticker.quarterly_income_stmt
        self.assertIs(data, data_cached, "data not cached")

```

2022-11-23 01:13 UTC, fredrik-corneliusson commented
> I propose returning this. Question - should user be alerted to switch? How?
Do you mean user should get a message informing on no data could be fetched with the new method and that they could try the old using a separate function? If that is the case I would very much advocate for that approach.

On a more general note.
A lot of effort has been put into cleaning up the code in order to make the code less bug prone, faster and easier on the yahoo requests. I'm afraid that if we begin adding quite high level if:s and but:s deep in the API it will quickly negate that effort and harm the project in the long run. 
I would suggest having a core API that is simple and flexible and if needed add a layers on top of it to create more specialized higher level APIs.

Just my 2 cents.

What are your thoughts?

2022-11-26 22:57 UTC, ValueRaider commented
I'm fine with the general note, just unsure about default behaviour. @git-shogg do you prefer automatic falling-back to old-format financials data with a message? Or should user have to specifically request via an argument?

2022-11-27 07:50 UTC, git-shogg commented
I think it's fine to revert back to the old format. You may have an issue with the camelcase function reading things that are in all caps (e.g. "EBITDA")? Is there an issue here or does it handle that ? Can always add the optional argument later.

2022-11-27 15:16 UTC, fredrik-corneliusson commented
Well automatic reverting back to old format will require much bigger change that current PR

2022-11-27 16:41 UTC, ValueRaider commented
Auto-reverting is actually simple. Add more getters to the fundamentals.py, and switching logic to base.py. I'll push soon.

2022-11-27 19:20 UTC, ValueRaider commented
Auto-reverting now improved - logic in `Ticker`, fetching refactored in `fundamentals.py`

2022-11-27 23:02 UTC, fredrik-corneliusson requested changes

2022-11-28 22:29 UTC, ValueRaider commented on yfinance/scrapers/fundamentals.py
> +                # Normally table only empty when nothing on Yahoo. So good?
It's meant as a rhetorical question - "If Yahoo not displaying a table anyway, is there actually a problem?"

2022-11-28 22:30 UTC, ValueRaider commented on yfinance/scrapers/fundamentals.py
> +                # Except 'QuoteSummaryStore' still contains the old financial data,
Old way of fetching

2022-11-28 22:31 UTC, ValueRaider commented on yfinance/scrapers/fundamentals.py
> +    def _create_financials_table_old(self, name, timescale, proxy):
Same columns, but different index and values. Mystery why Yahoo maintains two different tables for each financials.

2022-12-05 20:42 UTC, ValueRaider commented
@git-shogg Any opinion on this? Ideally can you try this branch, with a ticker that requires falling-back e.g. BSE.AX, then provide any feedback?

2022-12-10 21:13 UTC, ValueRaider commented
Removed the falling back, replaced with toggle argument defaulting to new format.

2022-12-10 21:13 UTC, merged