Fix datetime conversion with mixed timezones when ignore_tz is not False
ranaroussi/yfinance pull request #2016
Opened 2024-08-07 18:28 UTC by mreiche

When querying multi symbols at the same time, the Pandas Timestamp to datetime64 conversion will fail, when `utc=False`.
It looks like this is the most stable implementation, because Pandas suggests to use this feature in the future.
Downside: The original timezones are lost. But every datetime has now `tz=timezone.utc`
Upside: `ignore_tz` may be obsolete.

I added a test for testing Pandas datetime conversion as well.

2024-08-07 19:39 UTC, ValueRaider commented on tests/test_prices.py
> +import datetime as _dt
Pick one.

2024-08-07 19:40 UTC, ValueRaider requested changes

2024-08-07 19:40 UTC, ValueRaider commented on tests/test_prices.py
> +import datetime as _dt
Pick one

2024-08-07 19:40 UTC, ValueRaider commented
> Downside: The original timezones are lost. But every datetime has now `tz=timezone.utc`

That's fine as long as 9:30am EST is aligned with 2:30pm EU (or whatever the Atlantic offset is). `ignore_tz` means 9:30am EST aligned with 9:30am EU.

2024-08-08 05:01 UTC, mreiche commented
> > Downside: The original timezones are lost. But every datetime has now `tz=timezone.utc`
> 
> That's fine as long as 9:30am EST is aligned with 2:30pm EU (or whatever the Atlantic offset is). `ignore_tz` means 9:30am EST aligned with 9:30am EU.

That's covered by the test `PandasTest.test_mixed_timezones_to_datetime()` where the `datetime64` utc timestamps are compared to the tz-aware `Timestamps`.

2024-08-08 20:45 UTC, ValueRaider approved these changes

2024-08-08 20:45 UTC, ValueRaider commented
Approved. Just squash the commits #1084

2024-08-11 06:20 UTC, mreiche commented
> Approved. Just squash the commits #1084

Can't you just enable squash commits in your repo? https://docs.github.com/de/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/configuring-commit-squashing-for-pull-requests

2024-08-11 10:59 UTC, ValueRaider commented
Hmm. Could, but then the squashed commit message lists each individual commit e.g. `Add assertion for timezone`. Why would you not want to rewrite the message?

2024-08-12 05:01 UTC, mreiche commented
> Hmm. Could, but then the squashed commit message lists each individual commit e.g. `Add assertion for timezone`. Why would you not want to rewrite the message?

It's not something I usually do manually. I have to go back, rebase, commit everything again, force push. I don't even know how to do that. I need to read documentation, have several tries and so on. It just takes time. In Github, you can configure, if the MR title should be taken as Squash commit message. That takes less than 10 seconds.

2024-08-12 19:29 UTC, merged